### ISSUE TITLE
[RFC] Contribution Guideline

### ISSUE THREAD

**Issue by nsuthison** [rust-lang-th/book-th#2]
# [RFC] Contribution Guideline

Before we're going to start to translate the book into the Thai language, let us have a contribution guideline first so all of the contributions are in the same format and convention.

The conclusion after the discussion for the contribution guideline here is going to be our official contribution guideline for this project which will appear in Contributing.md file.

Please feel free to comments below if you have any ideas or questions.

**Note:** this RFC will end on **31 March 2021**. We'll finalize this version of the contribution guideline on **1st April 2021** and will release our first version in the same day.

----------------

# Contributing
Welcome to Rustlang book Thai translation project. Contributions to the project are always very welcome! 🙏🏽  

## Guideline
Have any questions? Feel free to ask in [our discussions](https://github.com/rust-lang-th/book-th/discussions) place. We're here to help!

## Translation
1. Please translate one chapter at a time from top to bottom. Jumping the translation between the context in the same chapter will make the other translator lose the context in the original language around the part that not translate yet.
3. When do the translation, please change only the texts and keep the style as same as the original version.
4. Keep transliteration words low, but if you think Thai word to describe that English word is not clear as the original one, you can decide to keep it untouched.
5. When in doubt, use the existing translation as the guideline.

## Submitting a pull request
One PR should contain only one chapter so the reviewer can focus only on that chapter also this will keep PR in a reasonable size to review.

### Commit message
For the commit message, use the following format:

```<type>::<chapter>::<line_number>::<subject(optional)>```

#### Types are
- `translate` :: Translate from the original language to Thai
- `change` :: Change incorrect translation which mean the meaning of the translation is going to change
- `fix` :: Fix typo in the translation
- `refined` :: Refined the word which already in Thai to be smoother to read but didn't change any meaning of it
- `format` :: Formatting texts or page

#### Chapter
Use the page type (chapter, appendix, forward, etc.) following the number of that kind of page. If there's no number specific for that kind of page, just use page type.

Example
- For _ch03-02-data-types.md_ use `ch03-02`
- For _appendix-04-useful-development-tools.md_ use `appendix-04`
- For _title-page.md_ use `title-page.md`

#### Line number
- If the change is only a single line, use format `<line_number>`
- If the change contains lines, use format as `<line_number_from>-<line_number_to>` (Note: There's a dash between these two line numbers)

Example
- For line number 5 use `5`
- For line number 5 to 27 use `5-27`

#### Subject (optional)
is a short description of what has been done

Example
- For _change_ chapter _appendix-01-keywords.md_ line number _5_ use `change::appendix-01::5`
- For _translate_ chapter _ch08-02-strings.md_ line number _19 to 42_ use `translate::ch08-02::19-42`

**Comment by dodadoa** [comment]
LGTM

**Comment by ARMnunf** [comment]
I think everything is OK but I think we not need to be communication with only English to make this project to be transparent to the public because We are translate this book to the Thai people and I think they have only Thai people will read this book that we translated. It will be better to communicate with Thai language to let Thai people that not good at English know what happen in this project and use English as less as possible, just use only essential and we should translate that English content to Thai if possible. This will make this project to be more transparent like the project that translate to Chinese and Japan language.

Chinese Language Translate: https://github.com/KaiserY/trpl-zh-cn
Japan Language Translate: https://github.com/rust-lang-ja/book-ja

**Comment by nsuthison** [comment]
> I think everything is OK but I think we not need to be communication with only English to make this project to be transparent to the public because We are translate this book to the Thai people and I think they have only Thai people will read this book that we translated. It will be better to communicate with Thai language to let Thai people that not good at English know what happen in this project and use English as less as possible, just use only essential and we should translate that English content to Thai if possible. This will make this project to be more transparent like the project that translate to Chinese and Japan language.
> 
> Chinese Language Translate: https://github.com/KaiserY/trpl-zh-cn
> Japan Language Translate: https://github.com/rust-lang-ja/book-ja

I discuss with @dodadoa and we're agree with you. Anyway, let use both language to communicate in this proj. I'll remove that point from the contribution guideline.

Thank you krub!

**Comment by dodadoa** [comment]
@ARMnunf ขอบคุณครับ 😄

**Comment by nsuthison** [comment]
Since this RFC is already pass the due date, I'll close this issue also create PR to submit our first contribution guideline.
